# Generated by Django 4.0.5 on 2022-06-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_users', '0003_remove_user_group_alter_user_sex_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='user_id',
            new_name='user',
        ),
    ]
