# Generated by Django 4.0.5 on 2022-06-13 08:51

from django.db import migrations, models
import network_users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('network_users', '0004_rename_group_id_members_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=16, unique=True, validators=[network_users.validators.NameValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=16, unique=True, validators=[network_users.validators.NameValidator()]),
        ),
    ]
